/* 퍼즐 그림 목록: 모두 저작권 보호 기간이 끝난 명화(작가 사망 후 70년 이상).
   t/a = 화면에 보이는 제목/작가, w/h = 이미지 픽셀 크기, source = 원본 출처.
   이미지는 가운데 기준 최대 4:3(세로는 3:4)으로 자르고, 긴 변 800px·JPEG 품질 80으로 줄였어요. */
window.PAINTINGS = [
  {"t": "양귀비 들판", "a": "클로드 모네", "src": "assets/paintings/01-monet-poppy-field.jpg", "w": 800, "h": 600, "enTitle": "Poppy Field", "enArtist": "Claude Monet", "artistDied": 1926, "source": "https://github.com/pmilovanov/hermitage-art (Monet,_Claude_-_Poppy_Field.jpg)"},
  {"t": "별이 빛나는 밤", "a": "빈센트 반 고흐", "src": "assets/paintings/02-van-gogh-starry-night.jpg", "w": 800, "h": 634, "enTitle": "The Starry Night", "enArtist": "Vincent van Gogh", "artistDied": 1890, "source": "https://github.com/jcjohnson/neural-style (examples/inputs/starry_night_google.jpg, Google Art Project)"},
  {"t": "꽃병의 장미와 한련", "a": "앙리 팡탱라투르", "src": "assets/paintings/03-fantin-latour-roses-nasturtiums.jpg", "w": 800, "h": 622, "enTitle": "Roses and Nasturtiums in a Vase", "enArtist": "Henri Fantin-Latour", "artistDied": 1904, "source": "https://github.com/pmilovanov/hermitage-art (Fantin-Latour,_Henri_-_Roses_and_Nasturtiums_in_a_Vase.jpg)"},
  {"t": "생타드레스 정원의 여인", "a": "클로드 모네", "src": "assets/paintings/04-monet-woman-in-garden.jpg", "w": 800, "h": 646, "enTitle": "Woman in the Garden, Sainte-Adresse", "enArtist": "Claude Monet", "artistDied": 1926, "source": "https://github.com/pmilovanov/hermitage-art (Monet,_Claude_-_Woman_in_the_Garden._Sainte-Adresse.jpg)"},
  {"t": "소나무 숲의 아침", "a": "이반 시시킨", "src": "assets/paintings/05-shishkin-morning-pine-forest.jpg", "w": 800, "h": 600, "enTitle": "Morning in a Pine Forest", "enArtist": "Ivan Shishkin", "artistDied": 1898, "source": "https://github.com/pmilovanov/hermitage-art (Shishkin,_Ivan_-_Morning_in_a_Pine_Forest.jpg)"},
  {"t": "부채를 든 소녀", "a": "피에르오귀스트 르누아르", "src": "assets/paintings/06-renoir-girl-with-fan.jpg", "w": 601, "h": 800, "enTitle": "Girl with a Fan", "enArtist": "Pierre-Auguste Renoir", "artistDied": 1919, "source": "https://github.com/pmilovanov/hermitage-art (Renoir,_Pierre-Auguste_-_Girl_with_a_Fan.jpg)"},
  {"t": "아홉 번째 파도", "a": "이반 아이바좁스키", "src": "assets/paintings/07-aivazovsky-ninth-wave.jpg", "w": 800, "h": 600, "enTitle": "The Ninth Wave", "enArtist": "Ivan Aivazovsky", "artistDied": 1900, "source": "https://github.com/pmilovanov/hermitage-art (Aivazovsky,_Ivan_-_The_Ninth_Wave.jpg)"},
  {"t": "지베르니의 건초더미", "a": "클로드 모네", "src": "assets/paintings/08-monet-haystack-giverny.jpg", "w": 800, "h": 600, "enTitle": "Haystack at Giverny", "enArtist": "Claude Monet", "artistDied": 1926, "source": "https://github.com/pmilovanov/hermitage-art (Monet,_Claude_-_Haystack_at_Giverny.jpg)"},
  {"t": "수련", "a": "클로드 모네", "src": "assets/paintings/09-monet-water-lilies.jpg", "w": 800, "h": 600, "enTitle": "Water Lilies (1919)", "enArtist": "Claude Monet", "artistDied": 1926, "source": "https://github.com/titu1994/Neural-Style-Transfer (images/inputs/style/water-lilies-1919-2.jpg)"},
  {"t": "몽마르트르 대로", "a": "카미유 피사로", "src": "assets/paintings/10-pissarro-boulevard-montmartre.jpg", "w": 800, "h": 630, "enTitle": "Boulevard Montmartre in Paris", "enArtist": "Camille Pissarro", "artistDied": 1903, "source": "https://github.com/pmilovanov/hermitage-art (Pissarro,_Camille_-_Boulevard_Monmartre_in_Paris.jpg)"}
];
